services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    command: ["/wait-for-it.sh", "db", "5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend:/code
    environment:
      DATABASE_URL: postgresql+asyncpg://trader:secret@db:5432/trading
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: